replicaCount: 1

image:
  repository: us.gcr.io/rlt-test/rlt-test
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - rlttest.ga
  tls: []


resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
